services:
  # This service runs the data ingestion script
  ingestion_script:
    build: .
    command: python scripts/data_ingestion.py # Explicit command
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=finml_data
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432

  # NEW: This service runs the model training script
  model_trainer:
    build: .
    command: python scripts/train_baseline_model.py # Command for this service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=finml_data
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432

  # The database service remains the same
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=finml_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: